### ISSUE TITLE
After installation there is a second front camera black spot 

### ISSUE THREAD

**Issue by idanny76** [Magisk-Modules-Alt-Repo/HideNavBar#13]
I cannot take a screenshot or a record screen. I guess I could take a picture with another phone. Let me know if you want a picture of the issue.

**Comment by idanny76** [comment]
It also changes the setting when you press and hold the power button from getting the restart menu to the Google assistant.

**Comment by DanGLES3** [comment]
Android version? GSI? GSIs are known to be randomly wonky with overlay modules and seem to break down when an new overlay is added 
(thus causing all device overlays to break and causing the afforementioned issues)

I've been unable to narrow down anything on my module that would cause such issue however 

Also sorry for taking so long to answer to your issue

**Comment by DanGLES3** [comment]
> I cannot take a screenshot or a record screen. I guess I could take a picture with another phone. Let me know if you want a picture of the issue.

If you wish try the latest release if you're on Android 12 or higher, it should fix your issues
