### ISSUE TITLE
Wried Headphone and Bluetooth Headphone not detect for GSI ROM

### ISSUE THREAD

**Issue by GuraNotFound** [Magisk-Modules-Alt-Repo/HideNavBar#15]
As title above, there is no sound in wired headset and bluetooth headset after installing on GSI ROM (based on phhusson gsi ROM)

**Comment by DanGLES3** [comment]
> As title above, there is no sound in wired headset and bluetooth headset after installing on GSI ROM (based on phhusson gsi ROM)

As stated in the module's disclaimer, due to the somewhat hacky nature of GSIs and Magisk's unwillingness to support these i unfortunately can't do much to fix this as it's not a module issue but a Magisk/GSI bug

**Comment by DanGLES3** [comment]
> As title above, there is no sound in wired headset and bluetooth headset after installing on GSI ROM (based on phhusson gsi ROM)

If you wish try the latest release if you're on Android 12 or higher, it should fix your issues
