### ISSUE TITLE
Google apps crash

### ISSUE THREAD

**Issue by ajpalasky1** [Magisk-Modules-Alt-Repo/HideNavBar#16]
When enabling this plugin on OOS 12 all Google related apps crash upon launch, Google search, Gmail, assistant, lens, Google services, and Google logins

**Comment by DanGLES3** [comment]
> When enabling this plugin on OOS 12 all Google related apps crash upon launch, Google search, Gmail, assistant, lens, Google services, and Google logins

If you wish try the latest release if you're on Android 12 or higher, it should fix your issues

**Comment by DanGLES3** [comment]
Closed due to lack of activity
