### ISSUE TITLE
where to download the module zip?

### ISSUE THREAD

**Issue by fusionneur** [Magisk-Modules-Alt-Repo/HideNavBar#17]
where to download the module zip?

**Comment by DanGLES3** [comment]
> i tried installing the module using "fox's magisk module manager" but magisk throws an error that it cannot unzip it

Try again and make sure your Fox Module Manager is up-to-date, it's working just fine on my end

**Comment by DanGLES3** [comment]
> do you install via fox module manager or you select the zip in magisk directly (what i did)?

Fox Module Mana

**Comment by DanGLES3** [comment]
> is there any other way to download the module without relying on Fox? I prefer flashing with magisk
> 
> Maybe it should be added as a release

I'll consider, tho understand that said releases may be delayed in updates as most users don't download a module straight from the repository

**Comment by DanGLES3** [comment]
> is there any other way to download the module without relying on Fox? I prefer flashing with magisk
> 
> Maybe it should be added as a release

[Fullscreen-Immersive Gestures-(Q-T)-v21.0-(54).zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/9477251/Fullscreen-Immersive.Gestures-.Q-T.-v21.0-.54.zip)

**Comment by DanGLES3** [comment]
Well, if you don't have further complaints i'll close this issue, if anything happens i'll reopen this
