### ISSUE TITLE
This had worked on A13, but after re-installing, this is no longer the case

### ISSUE THREAD

**Issue by Thisisauser6443** [Magisk-Modules-Alt-Repo/HideNavBar#19]
**Setup procedure/Reproducing issue**
- Immersive mode
- Hiding pill is set to `Yes`
- Both hiding and shortening KB buttons are set to `No`
- Gesture sensitivity is set to `High`
- Back gesture is kept

**Device and ROM**
Google Pixel 4a 5G (`bramble`) on a stock A13 image (`bramble-tp1a.220624.014`)

I had also had an attempt with Fullscreen mode, in case going for immersive was the issue, but it causes the same fallback method to 3 button navigation. Obviously, I know that A13 is still pretty new as a stable release, and the fact that most OEMs that don't have a similar frequency of updates like Google's, but I think this is worth mentioning

**Comment by DanGLES3** [comment]
> **Setup procedure/Reproducing issue**
> 
> * Immersive mode
> * Hiding pill is set to `Yes`
> * Both hiding and shortening KB buttons are set to `No`
> * Gesture sensitivity is set to `High`
> * Back gesture is kept
> 
> **Device and ROM** Google Pixel 4a 5G (`bramble`) on a stock A13 image (`bramble-tp1a.220624.014`)
> 
> I had also had an attempt with Fullscreen mode, in case going for immersive was the issue, but it causes the same fallback method to 3 button navigation. Obviously, I know that A13 is still pretty new as a stable release, and the fact that most OEMs that don't have a similar frequency of updates like Google's, but I think this is worth mentioning

Try installing the module again, v21 change how the module handles Android 12+ to prevent this fallback bug

**Comment by Thisisauser6443** [comment]
Yeah, that's done it for me. Ty :)
