### ISSUE TITLE
Navbar not hidden in landscape mode

### ISSUE THREAD

**Issue by AbdullahM0hamed** [Magisk-Modules-Alt-Repo/HideNavBar#20]
Android Version: 12.1
Module Version: 21.0
Device: Pixel 6
ROM: Stock

When this module is used to set the nav-bar's height to 0 - if 2-button nav or 3-button nav is enabled (instead of gestures), then the nav-bar will reappear whenever the device is in landscape mode (such as when watching a video).

Screenshots for demonstration:

Portrait:
![Screenshot_20220925-215650](https://user-images.githubusercontent.com/25087116/192165397-de92b574-3f00-4a8c-a8cb-62e2bf6a18ad.png)

Landscape:
![Screenshot_20220925-215746](https://user-images.githubusercontent.com/25087116/192165417-db5ca859-274b-4dce-a676-a4e778de1993.png)

**Comment by DanGLES3** [comment]
> Android Version: 12.1 Module Version: 21.0 Device: Pixel 6 ROM: Stock
> 
> When this module is used to set the nav-bar's height to 0 - if 2-button nav or 3-button nav is enabled (instead of gestures), then the nav-bar will reappear whenever the device is in landscape mode (such as when watching a video).
> 
> Screenshots for demonstration:
> 
> Portrait: ![Screenshot_20220925-215650](https://user-images.githubusercontent.com/25087116/192165397-de92b574-3f00-4a8c-a8cb-62e2bf6a18ad.png)
> 
> Landscape: ![Screenshot_20220925-215746](https://user-images.githubusercontent.com/25087116/192165417-db5ca859-274b-4dce-a676-a4e778de1993.png)

This module was not designed to hide the 2-3 button navigation bar
