### ISSUE TITLE
Not supported on 64-bit only systems

### ISSUE THREAD

**Issue by whezzel** [Magisk-Modules-Alt-Repo/HideNavBar#22]
I assume this is already known since this response is displayed when trying to install on a 64-bit only system

Are there any plans to support 64-bit only system? I would love to run this on my new Pixel 7 Pro.

**Comment by pritster5** [comment]
Strange, I'm using this on my Pixel 7 Pro with no real issues

**Comment by whezzel** [comment]
I use a module manager that seems to have an issue installing this module. When I saw your comment I downloaded the module and installed it through the magisk app just fine. I'm not sure why I didn't think yo try that sooner.
