### ISSUE TITLE
Full screen mode still leaves tiny white rectangles at the bottom

### ISSUE THREAD

**Issue by pritster5** [Magisk-Modules-Alt-Repo/HideNavBar#23]
Love this module but could you please fix those tiny white rectangles? Here's a picture of what I mean:

![Screenshot_20221017-181021](https://user-images.githubusercontent.com/7132319/196293922-e8b533a9-a896-400f-ba76-a95049126cfb.png)

**Comment by DanGLES3** [comment]
> Love this module but could you please fix those tiny white rectangles? Here's a picture of what I mean:
> 
> ![Screenshot_20221017-181021](https://user-images.githubusercontent.com/7132319/196293922-e8b533a9-a896-400f-ba76-a95049126cfb.png)

If you're using the Gcam lag fix option that's just a common side effect because to fix the Gcam lag a fraction of the navigation bar needs to be visible

**Comment by pritster5** [comment]
Actually I resolved the issue by hiding the navbar via an entirely different way:
Using this command in a .nk file inside data/adb/post-fs-data.d: resetprop qemu.hw.mainkeys 1

**Comment by DanGLES3** [comment]
> Actually I resolved the issue by hiding the navbar via an entirely different way: Using this command in a .nk file inside dabh the ta/adb/post-fs-data.d: resetprop qemu.hw.mainkeys 1
> 
> I haven't noticed any issues with the Gcam using this method to hide the navbar. (I'm using Vivid nav gestures for navigation)

T

> Actually I resolved the issue by hiding the navbar via an entirely different way: Using this command in a .nk file inside data/adb/post-fs-data.d: resetprop qemu.hw.mainkeys 1
> 
> I haven't noticed any issues with the Gcam using this method to hide the navbar. (I'm using Vivid nav gestures for navigation)

Tbh the issue with Gcam is slow mode switching, if that doesn't happen to you then great

**Comment by pritster5** [comment]
Oh shit, I didn't know that's what was meant by Gcam issue. Yeah, I'm definitely experiencing lag with my method. Why does that happen?

**Comment by pritster5** [comment]
Yeah it's really weird, because Snapchat and other camera apps work fine. Has the issue been reported to Google?

**Comment by DanGLES3** [comment]
> Yeah it's really weird, because Snapchat and other camera apps work fine. Has the issue been reported to Google?

Thing is, this issue only happens in a setup (hiding the navbar) that simply doesn't exist on a stock pixel (as Gcam is only officially available there)

So i don't think Google would consider this a valid report as this only happens when you tamper/mod a Pixel device (or use it on a third party device which Google doesn't support)

**Comment by pritster5** [comment]
That's a shame. For what it's worth, I submitted an issue on it anyways. Has any other developer (besides Google) looked into this? Perhaps someone from XDA?

**Comment by DanGLES3** [comment]
> That's a shame. For what it's worth, I submitted an issue on it anyways. Has any other developer (besides Google) looked into this? Perhaps someone from XDA?

None that I could find, for what's worth seems most people either don't notice or simply don't care about this issue enough to report/investigate it

I guess you could try reporting this to the developers of famous GCam mods to see if they can do anything at least on their modded APKs

**Comment by DanGLES3** [comment]
> That's a shame. For what it's worth, I submitted an issue on it anyways. Has any other developer (besides Google) looked into this? Perhaps someone from XDA?

As a workaround I could make a substratum theme to make those 3 lines disappear (i assume you're using 3 button navigation right?)

**Comment by pritster5** [comment]
It's all good, no need for the theme, I can live with the rectangles (or the lag in the camera app tbh, I don't take pictures that often). I'll try reaching out to the GCam Mod devs. 

Thanks for the info!

**Comment by DanGLES3** [comment]
> It's all good, no need for the theme, I can live with the rectangles (or the lag in the camera app tbh, I don't take pictures that often). I'll try reaching out to the GCam Mod devs.
> 
> Thanks for the info!

Best of luck to you, if you manage to get that fixed on GCam Mods be sure to notify me, I'd love to know that

**Comment by DanGLES3** [comment]
> It's all good, no need for the theme, I can live with the rectangles (or the lag in the camera app tbh, I don't take pictures that often). I'll try reaching out to the GCam Mod devs.
> 
> Thanks for the info!

Also tbh I'm already transitioning my module to substratum as it's just easier to maintain and way more reliable than my module could ever hope to be


Only reason why the module works so well now is because I'm using Android 12+ Fabricated Overlays feature however that limits what I can do to tweak the navigation bar (can't hide the buttons when the keyboard is opened for example) and that can't be applied to Android 10-11

**Comment by pritster5** [comment]
Actually the thought just occurred to me, do the rectangles have to be white? Can they be transparent?

**Comment by DanGLES3** [comment]
> Actually the thought just occurred to me, do the rectangles have to be white? Can they be transparent?

Are you using 3 button navigation?

**Comment by pritster5** [comment]
Yep

**Comment by DanGLES3** [comment]
> Yep

Then as i said previously i can make a substratum theme that creates a blank navigation bar layout without buttons, i'll need some time tho as i'm busy rn

**Comment by pritster5** [comment]
Oh ok no rush. Thank you for taking the time to do this!

**Comment by DanGLES3** [comment]
> Oh ok no rush. Thank you for taking the time to do this!

[app-release.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/9835744/app-release.zip)

Here it is, use Substratum Lite btw, on the SystemUI option choose the hide keyboard buttons feature, see if it works out for you

**Comment by pritster5** [comment]
Haha dude it's no worries at all, I was expecting something a few days from now, not a few hours. 

Thanks so much! This is immensely helpful.

**Comment by DanGLES3** [comment]
> Haha dude it's no worries at all, I was expecting something a few days from now, not a few hours.
> 
> Thanks so much! This is immensely helpful.

Be sure to tell me if it works out for you

**Comment by pritster5** [comment]
I'm on Android 13. Should I just get substratum lite off of the app store?

**Comment by DanGLES3** [comment]
> I'm on Android 13. Should I just get substratum lite off of the app store?

Yeah

**Comment by pritster5** [comment]
Substratum Lite crashed a short while after I launched it and gave it root permission.

**Comment by DanGLES3** [comment]
> Substratum Lite crashed a short while after I launched it and gave it root permission.

Try clearing its data and see if it works, I've seen other people on Android 13 use it just fine

**Comment by pritster5** [comment]
That fixed it. Do I have to uninstall your magisk module before testing this out?

**Comment by DanGLES3** [comment]
> That fixed it. Do I have to uninstall your magisk module before testing this out?

As long as you just tweak the options in the system UI you should have no need to

**Comment by pritster5** [comment]
Okay so unfortunately I uninstalled the Magisk module before using your substratum theme, but that's okay because the Android System portion behaves as expected with the nav bar mode set to "Fullscreen - GcamLagFix". However, even with the SystemUI set to "HidePill/Keyboard Buttons" I still see the three small white rectangles at the bottom.

**Comment by DanGLES3** [comment]
> Okay so unfortunately I uninstalled the Magisk module before using your substratum theme, but that's okay because the Android System portion behaves as expected with the nav bar mode set to "Fullscreen - GcamLagFix". However, even with the SystemUI set to "HidePill/Keyboard Buttons" I still see the three small white rectangles at the bottom.

Just to be sure, you've specifically chosen/installed the Hide Keyboard Buttons option right?

**Comment by pritster5** [comment]
Yep,  installed the Hide keyboard option, then I rebooted, then I enabled it and it had no effect.

**Comment by pritster5** [comment]
FWIW, the SystemUI overlay name in Substratum is in Red, while the Android System one is green

**Comment by DanGLES3** [comment]
> FWIW, the SystemUI overlay name in Substratum is in Red, while the Android System one is green

If it's red it's because it's disabled

**Comment by pritster5** [comment]
I see. However I found out that red means "disabled - invalid overlay" so I'm not even able to enable it.

![Screenshot_20221021-044007](https://user-images.githubusercontent.com/7132319/197152757-74a3d862-bdc3-4f00-aa33-96c867e98e21.png)
![Screenshot_20221021-044001](https://user-images.githubusercontent.com/7132319/197152759-4326a205-589f-457a-bd1b-6b10b209a846.png)

**Comment by DanGLES3** [comment]
> Ignore the selections

Gimme a minute

**Comment by DanGLES3** [comment]
> Ignore the selections

[app-release_src (1).zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/9837322/app-release_src.1.zip)

You'll have to uninstall the current APK, I'm not on my PC rn so i can't properly sign APKs

**Comment by pritster5** [comment]
Still facing the same issue. I'm able to hide the navbar and buttons but not the rectangles. SystemUi overlay is still red/invalid

**Comment by DanGLES3** [comment]
> Still facing the same issue. I'm able to hide the navbar and buttons but not the rectangles. SystemUi overlay is still red/invalid

Did you reinstall the overlays and reboot?

**Comment by pritster5** [comment]
Yep

**Comment by DanGLES3** [comment]
> Yep

Weird, overlays don't show as red here, when installing the system UI overlay, do any errors show up?

**Comment by DanGLES3** [comment]
> Yep

Btw i think i see the issue, you don't seem to be selecting anything in the system UI option 

Even the manage option just shows a blank system UI overlay with no description of it's option

**Comment by pritster5** [comment]
Ahh I see. Ok so I set it to hide buttons and then rebooted and now everything is green. I enabled both, but I can still see the white rectangles.

**Comment by DanGLES3** [comment]
> Ahh I see. Ok so I set it to hide buttons and then rebooted and now everything is green. I enabled both, but I can still see the white rectangles.

Try the previous APK now, see if it works, if not I'll ask you for you to wait until tomorrow as it's now 6am and I'm severely exhausted rn

**Comment by pritster5** [comment]
Oh jeez, yeah no need to get this done right now, please rest lol. 
I have just tried the old APK and selected options for both. Everything is green and I still see the white rectangles.

**Comment by DanGLES3** [comment]
> Oh jeez, yeah no need to get this done right now, please rest lol. I have just tried the old APK and selected options for both. Everything is green and I still see the white rectangles.

[app-release.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/9840376/app-release.zip)

You'll need to enable the no gestures option in the system framework (make sure to also install the fullscreen overlay)

**Comment by pritster5** [comment]
Yes this would work. But hmm I don't see a "no gestures" option for Android System. I do see (and have disabled) the back gestures from within your APK.

**Comment by pritster5** [comment]
Also would I use the "hide pill" option now for SystemUI?

**Comment by DanGLES3** [comment]
> Yes this would work. But hmm I don't see a "no gestures" option for Android System. I do see (and have disabled) the back gestures from within your APK.

Gimme a sec, guess I've sent the wrong apk

**Comment by DanGLES3** [comment]
> Also would I use the "hide pill" option now for SystemUI?

[app-release2.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/9840782/app-release2.zip)

**Comment by DanGLES3** [comment]
> Also quick question: how do I reenable the back gesture after disabling it from within your app? I uninstalled your APK but forgot to turn it back on and now the left side of my screen can't back gesture, even after reboot.
> 
> Funnily enough, this actually fixed one of the reasons I didn't like the Pixel 7 Pro's gestures in the first place, which is that apps with a hamburger menu can't use the "swipe in from left to pull in the menu" gesture.

Just reinstall the app and turn it back on from there

**Comment by pritster5** [comment]
That did it, thanks so much! No Gcam app lag, I'm able to use the vivid gestures I configured and everything works!

Out of curiosity, how was your app disabling the back gesture from within the APK? When I granted it root access, what was it modifying? 

Because lowkey, if I could just disable the left side back gesture, the native Pixel gestures work perfectly.

**Comment by DanGLES3** [comment]
> That did it, thanks so much! No Gcam app lag, I'm able to use the vivid gestures I configured and everything works!
> 
> Out of curiosity, how was your app disabling the back gesture from within the APK? When I granted it root access, what was it modifying?
> 
> Because lowkey, if I could just disable the left side back gesture, the native Pixel gestures work perfectly.

Well since Android 11, Android determines the sensitivity of the back gesture based on a settings value (back_gesture_inset_scale_right and back_gesture_inset_scale_left), turns out setting either to a negative value (such as -1) basically disables the back gesture for that side

**Comment by DanGLES3** [comment]
> That did it, thanks so much! No Gcam app lag, I'm able to use the vivid gestures I configured and everything works!
> 
> Out of curiosity, how was your app disabling the back gesture from within the APK? When I granted it root access, what was it modifying?
> 
> Because lowkey, if I could just disable the left side back gesture, the native Pixel gestures work perfectly.

Tbh, if all you want is to disable the back gestures and use the native system gestures, just disable the substratum overlays and disable the back gesture on the left for hamburger menus

**Comment by pritster5** [comment]
Got it. I was just wondering if I could do this without any apps installed for cleanliness sake.

For example, I used "resetprop qemu.hw.mainkeys 1" to hide the navbar (which caused the Gcam bug). Is there any command like that that I could put in a file to disable the left side back gesture? And also one to hide the gesture nav bar?

**Comment by DanGLES3** [comment]
> Got it. I was just wondering if I could do this without any apps installed for cleanliness sake.
> 
> For example, I used "resetprop qemu.hw.mainkeys 1" to hide the navbar (which caused the Gcam bug). Is there any command like that that I could put in a file to disable the left side back gesture? And also one to hide the gesture nav bar?

Tbh, after disabling the back gesture you can just remove the app, it doesn't need to be there anymore after you disable it


As for hiding the gesture nav bar, that needs a theme or a module

**Comment by pritster5** [comment]
Ah I see. I'm curious though, how is the app able to persist in its disabling of the back gesture even after uninstall?

**Comment by DanGLES3** [comment]
> Ah I see. I'm curious though, how is the app able to persist in its disabling of the back gesture even after uninstall?

It changes a system setting and that setting persists through reboots like any other system settings 

if you're that curious it basically runs the following command as root

settings put secure back_gesture_inset_scale_left (or right) -1

**Comment by pritster5** [comment]
Ah cool. Thanks for the info! This whole thing really made my life a lot easier.

**Comment by DanGLES3** [comment]
> Ah cool. Thanks for the info! This whole thing really made my life a lot easier.

Happy to help :)

**Comment by pritster5** [comment]
Hey man, just wanted to clarify something. Does the system setting you tweak modify the `/system` partition in any way? 

I followed [this](https://topjohnwu.github.io/Magisk/ota.html) guide by the Magisk creator and he states: "NOTE: In order to apply OTAs, you HAVE to make sure you haven’t modified and read-only partitons yourself (such as /system or /vendor) in any way. Even remounting the partition to rw will tamper block verification!!"

I'm asking because I followed the guide and now my phone is giving me a "Your device is corrupt" warning and is stuck on the Google logo on reboot.

**Comment by DanGLES3** [comment]
> Hey man, just wanted to clarify something. Does the system setting you tweak modify the `/system` partition in any way?
> 
> I followed [this](https://topjohnwu.github.io/Magisk/ota.html) guide by the Magisk creator and he states: "NOTE: In order to apply OTAs, you HAVE to make sure you haven’t modified and read-only partitons yourself (such as /system or /vendor) in any way. Even remounting the partition to rw will tamper block verification!!"
> 
> I'm asking because I followed the guide and now my phone is giving me a "Your device is corrupt" warning and is stuck on the Google logo on reboot.

The setting in no way needs to tamper with the system partition, it's a regular setting like any other

**Comment by pritster5** [comment]
Where does the setting live? Sorry I'm unfamiliar when it comes to system settings.

**Comment by DanGLES3** [comment]
> Where does the setting live? Sorry I'm unfamiliar when it comes to system settings.

Where every other system setting lives /data/system/user/0/

**Comment by pritster5** [comment]
And I did do this: "Using this command in a .nk file inside data/adb/post-fs-data.d: resetprop qemu.hw.mainkeys 1". 

Would that modify **any read-only partitions** in any way?
I'm assuming `/data/...` is not read only.

**Comment by DanGLES3** [comment]
> And I did do this: "Using this command in a .nk file inside data/adb/post-fs-data.d: resetprop qemu.hw.mainkeys 1".
> 
> Would that modify **any read-only partitions** in any way? I'm assuming `/data/...` is not read only.

/Data is where every user setting, installed app and whatnot is stored, and no, resetprop commands do not tamper with any partitions whatsoever as that's all done in memory

**Comment by pritster5** [comment]
Ok perfect, thank you for explaining. This helps me narrow it down and at least this stuck bootup isn't a fault of my own haha.
