### ISSUE TITLE
Google camera lag 

### ISSUE THREAD

**Issue by afstudios** [Magisk-Modules-Alt-Repo/HideNavBar#26]
Everything works well except Google camera which has some lag, no matter the height set to 30 or 100.

**Comment by boehs** [comment]
Yep been happening for months

**Comment by boehs** [comment]
Just updated and it fixes the gcam lag but systemui isn't responding

**Comment by boehs** [comment]
Closed out of system UI, that was fine. Did `su -c hn` to fix the keyboard height back and gcam is laggy again

**Comment by boehs** [comment]
Started using asop mods hide navbar, works perfectly, but downside is it also hid Gboard controls

**Comment by boehs** [comment]
Sorry, last one

Also see https://github.com/siavash79/AOSPMods/issues/414

**Comment by DanGLES3** [comment]
> Everything works well except Google camera which has some lag, no matter the height set to 30 or 100.

Both the navigation bar and keyboard bar height need to be at least above 0

It needs to be set to both

**Comment by DanGLES3** [comment]
Closed due to lack of activity
