### ISSUE TITLE
LineageOS Installation without Volume Keys

### ISSUE THREAD

**Issue by TheEmeraldKytten** [Magisk-Modules-Alt-Repo/HideNavBar#31]
I'm trying to install this module on LineageOS 20 running on my Raspberry Pi 4b. I do not have volume buttons. The F11/F12 volume rocker simulation doesn't seem to work, as the module says I didn't press anything and fails out.

I've also tried doing this using ADB, but it's the same thing. Alt+Down Arrow (simulates volume down) doesn't work, same thing with Alt+Up Arrow. Am I doing something wrong, or is it impossible to install this way

**Comment by DanGLES3** [comment]
If you wish an install doesn't use volume buttoms i'd recommend using the substratum version of this and apply it using Substratum Lite[
[FSIM-Version-1.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/10328074/FSIM-Version-1.zip)
](url)

**Comment by DanGLES3** [comment]
Closed due to lack of activity/response
