### ISSUE TITLE
Corner gestures reappear after opening camera or using always on display

### ISSUE THREAD

**Issue by jhrush** [Magisk-Modules-Alt-Repo/HideNavBar#32]
![image8](https://user-images.githubusercontent.com/60750922/211143800-7eeaae84-f577-43c3-afaa-244afe0b166c.png)

Using a Motorola phone on android 11. After opening the camera from lockscreen the corner pieces of gesture navigation reappear. Although they go away again if I use the corner gesture

**Comment by DanGLES3** [comment]
> ![image8](https://user-images.githubusercontent.com/60750922/211143800-7eeaae84-f577-43c3-afaa-244afe0b166c.png)
> 
> Using a Motorola phone on android 11. After opening the camera from lockscreen the corner pieces of gesture navigation reappear. Although they go away again if I use the corner gesture

What mode are you using? Fullscreen or Immersive?

**Comment by DanGLES3** [comment]
> Also note that this bug doesn't occur in fullscreen mode, the only problem with that is that you lose the more granular tuning of immersive mode, namely the keyboard bar.

Yeah, so far it seems like those corner gestures are handled entirely in code so I can't seem to be able to remove them

**Comment by DanGLES3** [comment]
> I wonder how fullscreen mode 'solves' it. I'm guessing they're still there they are just offscreen?


If i were to guess, those are being displayed on the navigation bar frame, as Fullscreen also hides the spacing underneath the keyboard it'll hide the navigation bar frame by setting it to 0 in height

**Comment by DanGLES3** [comment]
Closed due to lack of activity/response
