### ISSUE TITLE
Markup app is broken

### ISSUE THREAD

**Issue by alabotski** [Magisk-Modules-Alt-Repo/HideNavBar#34]
I installed this module 
Everything works fine except one app
Google Markup application is broken

https://support.google.com/pixelphone/thread/197772518?hl=en

![Screenshot_20230119-054815](https://user-images.githubusercontent.com/439337/213351778-dce74f63-ebf8-457b-a334-104f8e10a98d.png)
![Screenshot_20230119-054946](https://user-images.githubusercontent.com/439337/213351785-a99f2a6a-f5c6-4abb-8307-91a833f29ca8.png)

**Comment by DanGLES3** [comment]
> I installed this module Everything works fine except one app Google Markup application is broken
> 
> https://support.google.com/pixelphone/thread/197772518?hl=en
> 
> ![Screenshot_20230119-054815](https://user-images.githubusercontent.com/439337/213351778-dce74f63-ebf8-457b-a334-104f8e10a98d.png) ![Screenshot_20230119-054946](https://user-images.githubusercontent.com/439337/213351785-a99f2a6a-f5c6-4abb-8307-91a833f29ca8.png)

You need immersive and probably the Gcam lag fix as well, not much i can do for fullscreen as that's a bug on the Markup app
