### ISSUE TITLE
Pill is not hidden in tablet mode

### ISSUE THREAD

**Issue by matejdro** [Magisk-Modules-Alt-Repo/HideNavBar#38]
Steps to reproduce:

1. Run `adb shell wm density` and note down original density so you can revert the change later
2. Lower the density of your device enough to enter tablet mode (`adb shell wm density 380` for Pixel 7 Pro, use higher number if necessary) - you will recognize tablet mode by constant taskbar at the bottom
3. Hold your finger on any blank spot on the taskbar - it should turn into a pill
4. Install HideNavBar module with `Immersive (Without the Pill + Default Keyboard Spacing)` config 

Pill will still be visible.

**Comment by DanGLES3** [comment]
> Steps to reproduce:
> 
> 1. Run `adb shell wm density` and note down original density so you can revert the change later
> 2. Lower the density of your device enough to enter tablet mode (`adb shell wm density 380` for Pixel 7 Pro, use higher number if necessary) - you will recognize tablet mode by constant taskbar at the bottom
> 3. Hold your finger on any blank spot on the taskbar - it should turn into a pill
> 4. Install HideNavBar module with `Immersive (Without the Pill + Default Keyboard Spacing)` config
> 
> Pill will still be visible.

Check the latest versions

**Comment by matejdro** [comment]
Tried KSU-Test-3 with:

* Immersive
* Hide keyboard buttons
* Reduce size of the keyboard bar
* Low gesture sensitivity
* No Gcam fix
* Do NOT disable back gesture

And issue persists.

**Comment by DanGLES3** [comment]
> Tried KSU-Test-3 with:
> 
> * Immersive
> * Hide keyboard buttons
> * Reduce size of the keyboard bar
> * Low gesture sensitivity
> * No Gcam fix
> * Do NOT disable back gesture
> 
> And issue persists. Pill is hidden in phone mode, but appears when transitioning to tablet mode.

https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/12862190/revamp.zip

Try this version

**Comment by DanGLES3** [comment]
> Tried KSU-Test-3 with:
> 
> * Immersive
> * Hide keyboard buttons
> * Reduce size of the keyboard bar
> * Low gesture sensitivity
> * No Gcam fix
> * Do NOT disable back gesture
> 
> And issue persists. Pill is hidden in phone mode, but appears when transitioning to tablet mode.

Send the Pixel 7 gesture overlays in /product/overlays and I'll work on it tomorrow morning

**Comment by matejdro** [comment]
Thanks for looking into it.

Here is regular mode:

![image](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/assets/507922/7f224077-2a31-47c3-8017-4126b7f3a556)

And here is tablet mode (I've disabled the taskbar to make it clearer):

![image](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/assets/507922/52f1d0a8-5486-4b0f-9c0f-67d245e8da68)

Only difference between those images is the DPI. I've sent you the requested overlay files via Telegram, since they are quite big.
