### ISSUE TITLE
Support Android 14, API level 35

### ISSUE THREAD

**Issue by aurora1369** [Magisk-Modules-Alt-Repo/HideNavBar#41]

**Comment by kubo6472** [comment]
I just received an update to Android 14 and the pill is back. What needs to be done to properly support this?

**Comment by DanGLES3** [comment]
I've just released an update which should support Android 14

**Comment by kubo6472** [comment]
Thank you, will try and report back

**Comment by kubo6472** [comment]
Works, thanks
