### ISSUE TITLE
Black flickering screen Android 13

### ISSUE THREAD

**Issue by mrgnex** [Magisk-Modules-Alt-Repo/HideNavBar#42]
When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example).
A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).

**Comment by DanGLES3** [comment]
> When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example). A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).

Not sure what could be causing this issue as it's just resizing the navbar, i can only guess it might be a grapheneos issue

**Comment by DanGLES3** [comment]
> When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example). A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).

Btw is the problem both in fullscreen and immersive mode?

**Comment by mrgnex** [comment]
> > When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example). A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).
> 
> Btw is the problem both in fullscreen and immersive mode?

It's on both the stock ROM and GrapheneOS. I did get the same issue without the module but way less often. I will test the fullscreen setting now and report back!

**Comment by DanGLES3** [comment]
> > > When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example). A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).
> > 
> > 
> > Btw is the problem both in fullscreen and immersive mode?
> 
> It's on both the stock ROM and GrapheneOS. I did get the same issue without the module but way less often. I will test the fullscreen setting now and report back!

That's sounding more like a device issue if it happened even on stock without the module

**Comment by DanGLES3** [comment]
> > > When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example). A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).
> > 
> > 
> > Btw is the problem both in fullscreen and immersive mode?
> 
> It's on both the stock ROM and GrapheneOS. I did get the same issue without the module but way less often. I will test the fullscreen setting now and report back!

[revamp.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/12862190/revamp.zip)

See if the issue happens on this version

**Comment by mrgnex** [comment]
> > > > When using my Pixel 6 Pro and this module on both the stock OS and Graphene OS I get a black flickering screen after about 2 days of usage. The issue gets progressively worse until the screen sometimes stays black (until I swipe up to go to the homescreen for example). A reboot fixes the problem. It does not seem to be linked to certain apps although I have a suspicion it's worse when using my keyboard (both Gboard and OpenBoard) or when viewing my tabs in my browser (IceRaven).
> > > 
> > > 
> > > Btw is the problem both in fullscreen and immersive mode?
> > 
> > 
> > It's on both the stock ROM and GrapheneOS. I did get the same issue without the module but way less often. I will test the fullscreen setting now and report back!
> 
> [revamp.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/12862190/revamp.zip)
> 
> See if the issue happens on this version

Been running this since a day after you posted it and it's been working great so far!

**Comment by DanGLES3** [comment]
Great, thanks for testing
