### ISSUE TITLE
Keyboard not working 

### ISSUE THREAD

**Issue by milesueee** [Magisk-Modules-Alt-Repo/HideNavBar#43]
Hi! there seems to be a bug whenever I change my width dp in the Developer Settings. whenever I set my width dp higher or lower than 411, the screen can't be touched when the keyboard is open. any keyboard will not work/can't be touched.

Device: LG V50 ThinQ
Android Version: 12
Magisk Version: 26.3

**Comment by milesueee** [comment]
[Minimum Width Screen Record](https://drive.google.com/file/d/1Br6WqxdFz0XR6s2WucjISV1FGhkizFPY/view?usp=drivesdk) 

Also, when activating/deactivating dark mode triggers the bug. The only way to fix it is to restart the device

[Dark Mode Screen Record](https://drive.google.com/file/d/1Btr92GrLV8Ejnw2j2Y-lp_6Cou--q-yU/view?usp=drivesdk)

**Comment by DanGLES3** [comment]
> [Minimum Width Screen Record](https://drive.google.com/file/d/1Br6WqxdFz0XR6s2WucjISV1FGhkizFPY/view?usp=drivesdk)
> 
> Also, when activating/deactivating dark mode triggers the bug. The only way to fix it is to restart the device
> 
> [Dark Mode Screen Record](https://drive.google.com/file/d/1Btr92GrLV8Ejnw2j2Y-lp_6Cou--q-yU/view?usp=drivesdk)

That looks like a system bug tbh, does it happen in both fullscreen and immersive mode?

**Comment by DanGLES3** [comment]
> [Minimum Width Screen Record](https://drive.google.com/file/d/1Br6WqxdFz0XR6s2WucjISV1FGhkizFPY/view?usp=drivesdk)
> 
> Also, when activating/deactivating dark mode triggers the bug. The only way to fix it is to restart the device
> 
> [Dark Mode Screen Record](https://drive.google.com/file/d/1Btr92GrLV8Ejnw2j2Y-lp_6Cou--q-yU/view?usp=drivesdk)

[revamp.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/12862194/revamp.zip)

See if the issue happens on this version

**Comment by milesueee** [comment]
The bug still persists but only on Fullscreen. When I Tried "Immersive", the issue is resolved. I'll just stick to Immersive mode. Thank you!!
