### ISSUE TITLE
API MAX 34 

### ISSUE THREAD

**Issue by Sunbelife** [Magisk-Modules-Alt-Repo/HideNavBar#47]
I can't install this in API 34

**Comment by Hungermanw3t** [comment]
I have the same issue. Install script says it only supports up to API 33.

**Comment by DanGLES3** [comment]
> They are working on it, check the commits.

Should have already been fixed since release 23.0

**Comment by DanGLES3** [comment]
> @DanGLES3 I did that it and while it didn't brick my phone, the fullscreen feature (minimizing the space between keyboard and the bottom screen) did NOT work at all. Unfortunately. Another shame is that you don't put your latest releases here, like you just said. Why is that- I don't like any of the currently available module managers.

Are you using Magisk or KernelSU? Also I don't put releases here mostly cause of lazyness, I'll publish the latest release here later today, rn I need to rest a bit from work

**Comment by DanGLES3** [comment]
> @DanGLES3 Magisk, official 26.3.

What's your device and Android version? Also could you send a screenshot of how your navigation bar and keyboard looks like?

**Comment by DanGLES3** [comment]
Done, published the release on the releases page for those who don't want to use module managers
