### ISSUE TITLE
Terminal setup not working on version 24

### ISSUE THREAD

**Issue by IZ2QDH** [Magisk-Modules-Alt-Repo/HideNavBar#50]
Precondition:
v24 installed

Steps to reproduce:
- Open terminal (Termux in my case)
- Send command "su -c hn"

Expected:
Terminal setup initiated

Actual:
I get the error "hn not found or inaccessible"

On v21 terminal setup works

Device: Poco F1 (beryllium)
Android Version: 13 (LineageOS 20)
Magisk Version: 26.3

**Comment by cozykitten** [comment]
Seconding this, I don't know how to set a custom keyboard height despite being in fullscreen & hide pill mode.

Device information
Device: Pixel 6a
OS: A14 231205 (December OTA)
App version: v24
Magisk version: 26.4

**Comment by DanGLES3** [comment]
it's a known issue, haven't had the time to work it for now

**Comment by DanGLES3** [comment]
Terminal setup will be reintroduced at a later (still not planned) date
