### ISSUE TITLE
Pill/white bar not able to hide in Immersive mode (pixel 7 pro A14) 

### ISSUE THREAD

**Issue by tbv2005** [Magisk-Modules-Alt-Repo/HideNavBar#52]
Not sure if doing something wrong, but I'm not able to hide the white bar in Immersive mode, regardless if which option I choose. Preferable I want to remove the white bar with the smaller space for the keyboard and buttons removed. Smaller space and buttons removed working fine, but can't get rid of the ehite bar/pill. The only way I found to hide the white bar/pill is fullscreen, but then you have problem with back gesture for the bottom keyboard row. 

Stock Pixel 7 Pro with latest A14

**Comment by tbv2005** [comment]
Ok, small update I got it to work but in a bit wierd way. Problem seems to be with the "non display cutout" module also that one finally resolved. I disabled yours and the non display cut out. Rebooted, installed yours and the white bar was still there, then enabled the non display cut out again, rebooted, changed the cutout setting in developer options to the modul option and suddenly the white bar was gone.

**Comment by DanGLES3** [comment]
So, is this solved or not?

**Comment by tbv2005** [comment]
Yes it is {except the keyboard buttons not hiding as mentioned in the release notes) thank you!

**Comment by DanGLES3** [comment]
Good to know

**Comment by gianmarcotoso** [comment]
@DanGLES3 I'm also using a Pixel 7 Pro with Android 14 and I don't use the "non display cutout" module (I'm not sure what that is). Using immersive mode and selecting to hide the pill without affecting the keyboard's height, the pill remains visible on a transparent background, which is better than the default behavior but still a little bit invasive as it covers the bottom part of any app's interface. 

The other modules I've got installed are Play Integrity Fix and Systemless Host. Is there some info or log I can provide to help find the reason why this happens and hopefully implement a fix? Thanks.

**Comment by DanGLES3** [comment]
> @DanGLES3 I'm also using a Pixel 7 Pro with Android 14 and I don't use the "non display cutout" module (I'm not sure what that is). Using immersive mode and selecting to hide the pill without affecting the keyboard's height, the pill remains visible on a transparent background, which is better than the default behavior but still a little bit invasive as it covers the bottom part of any app's interface.
> 
> The other modules I've got installed are Play Integrity Fix and Systemless Host. Is there some info or log I can provide to help find the reason why this happens and hopefully implement a fix? Thanks.

Made sure you are using the latest version of the module?

**Comment by gianmarcotoso** [comment]
> > @DanGLES3 I'm also using a Pixel 7 Pro with Android 14 and I don't use the "non display cutout" module (I'm not sure what that is). Using immersive mode and selecting to hide the pill without affecting the keyboard's height, the pill remains visible on a transparent background, which is better than the default behavior but still a little bit invasive as it covers the bottom part of any app's interface.
> > The other modules I've got installed are Play Integrity Fix and Systemless Host. Is there some info or log I can provide to help find the reason why this happens and hopefully implement a fix? Thanks.
> 
> Made sure you are using the latest version of the module?

Yes, I've posted this after installing v25, with the previous version the pill was disappearing but the space below the keyboard was not being preserved.

**Comment by gianmarcotoso** [comment]
Update: I've uninstalled the module, rebooted, reinstalled the module and this time it worked. All's well, thanks :)
