### ISSUE TITLE
What about status bar ?

### ISSUE THREAD

**Issue by foxjaw** [Magisk-Modules-Alt-Repo/HideNavBar#53]
There are two implementations in Android.  

One is kiosk mode, which hides status bar & pulls the app into the space. In this mode, you can swipe down & make it reappear for a while & swipe down again intermediately to get to notifications. Usually, this method only works on applications. So I don't think you can do this on system UI. But can be done on the launcher you're using.   

Another is reducing the status bar height to 0, which completely hides it, so you can't even swipe down quick settings & notifications. Here the only way to access them would be using a gesture launcher like fluid navigation. And should rely on other methods to know your time, signal, battery, etc. This method is permanent & you gotta say tata to your stato bar.

**Comment by RadioactivePlays** [comment]
Would be useful to fully hide the status bar to prevent burn in on OLED/AMOLED/pOLED screens.

**Comment by DanGLES3** [comment]
That's not the goal of the module, and i don't wish for the module to have feature creep
