### ISSUE TITLE
Does Not Work W/ Android 14 QPR2 Beta 2

### ISSUE THREAD

**Issue by FrenchToucan** [Magisk-Modules-Alt-Repo/HideNavBar#54]
The wizard works but after restarting the device, the pill is still present. Tried immersive and full screen.

**Comment by EwanMac3** [comment]
Same here, 8 Pro.

**Comment by M7MDE7EGAZY** [comment]
same on realme gt 2 pro

**Comment by robotfishe** [comment]
Also seeing this on Pixel Fold.

**Comment by exolon** [comment]
Same here. v23 actually worked for me, today I updated and lost its functionality!

**Comment by YoshiFan501** [comment]
@exolon Do you still have a copy of the v23 zip?

**Comment by exolon** [comment]
> @exolon Do you still have a copy of the v23 zip?

Sadly, no 😐

**Comment by YoshiFan501** [comment]
Darn. I am also having issues with the latest one on AMM where the pill isn't hiding at all. I had to go back to v21 on my Pixel 8 Pro, but that one has issues it seems with not keeping the black bar height even if checking.

Hoping a fix is out soon

**Comment by exolon** [comment]
> Darn. I am also having issues with the latest one on AMM where the pill isn't hiding at all. I had to go back to v21 on my Pixel 8 Pro, but that one has issues it seems with not keeping the black bar height even if checking.
> 
> Hoping a fix is out soon

Damnit... A pity older versions have been removed!

**Comment by robotfishe** [comment]
> Same here. v23 actually worked for me, today I updated and lost its functionality!

Thanks to your comment I was able to get mine working! Download the "A14 test 3" version from the Telegram group, install using "immersive" option. Need to have OS navigation set to gesture first. CAUTION: MY DEVICE BOOTLOOPED ONCE but then booted fine on its second attempt with no interaction from me. However, no guarantees yours won't bootloop forever.

**Comment by exolon** [comment]
> > Same here. v23 actually worked for me, today I updated and lost its functionality!
> 
> Thanks to your comment I was able to get mine working! Download the "A14 test 3" version from the Telegram group, install using "immersive" option. Need to have OS navigation set to gesture first. CAUTION: MY DEVICE BOOTLOOPED ONCE but then booted fine on its second attempt with no interaction from me. However, no guarantees yours won't bootloop forever.

Bootloops I can handle, if I can recall the name of the TG group😂

Thanks for reporting, will try!

**Comment by exolon** [comment]
> > Same here. v23 actually worked for me, today I updated and lost its functionality!
> 
> Thanks to your comment I was able to get mine working! Download the "A14 test 3" version from the Telegram group, install using "immersive" option. Need to have OS navigation set to gesture first. CAUTION: MY DEVICE BOOTLOOPED ONCE but then booted fine on its second attempt with no interaction from me. However, no guarantees yours won't bootloop forever.

By the way, test 4 didn't work? Only test 3?

**Comment by exolon** [comment]
A new release in the TG channel seems to work with QPR2b2 so, yay!

**Comment by robotfishe** [comment]
> A new release in the TG channel seems to work with QPR2b2 so, yay!

KSU Test 4 doesn't work for me. Seems to install correctly, but gesture pill is still visible. Pixel fold on 14 QPR2 beta 1, Magisk 26.4.

**Comment by exolon** [comment]
> > A new release in the TG channel seems to work with QPR2b2 so, yay!
> 
> KSU Test 4 doesn't work for me. Seems to install correctly, but gesture pill is still visible. Pixel fold on 14 QPR2 beta 1, Magisk 26.4.

Hmm for me it worked with the Immersive setting... Using Delta/kitsune

**Comment by DanGLES3** [comment]
Should be fixed in version 25
