### ISSUE TITLE
In some applications, there are a few pixels of white lines at the bottom of the screen.

### ISSUE THREAD

**Issue by heli-0604** [Magisk-Modules-Alt-Repo/HideNavBar#55]
the v21 version can be hidden and almost perfect (-+--+-)；
but sometimes some applications will display a white line with a few pixels at the bottom ；
On pixel 4xl Android 13 ,hope it can be solved；

**Comment by EwanMac3** [comment]
Turn off the GCam lag fix and it won't have the bar at the bottom

**Comment by DanGLES3** [comment]
That's a side effect of using the Gcam lag fix, it needs to keep a fraction of the navbar visible, nowadays the Gcam lag fix shouldn't be needed in most cases
