### ISSUE TITLE
Sometimes "System Interface" crashes

### ISSUE THREAD

**Issue by person10301** [Magisk-Modules-Alt-Repo/HideNavBar#56]
[log.txt](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13527977/log.txt)

**Comment by DanGLES3** [comment]
What device and when exactly does it crash?

**Comment by person10301** [comment]
Poco F5 Pro
Pixel experience
It’s not clear when exactly, it was random, but so far it doesn’t seem to have appeared again

**Comment by person10301** [comment]
Poco F5 Pro
Pixel experience
It’s not clear when exactly, it was random, but so far it doesn’t seem to have appeared again

**Comment by DanGLES3** [comment]
> Poco F5 Pro Pixel experience It’s not clear when exactly, it was random, but so far it doesn’t seem to have appeared again

Good to know, because tbh the crash seems more like a hang of unknown origin, seems somewhat related to resizing the PIP window (at least that's what the logs indicate)

**Comment by person10301** [comment]
Today for some reason the home/recent gesture stopped working temporarily, then it started working after I went into the settings (but it seems to me that this is a coincidence)...
[log.txt](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13758872/log.txt)
