### ISSUE TITLE
Issues with Magisk Canary 26.4 (26403) (d7750b72)

### ISSUE THREAD

**Issue by innit86** [Magisk-Modules-Alt-Repo/HideNavBar#57]
It no longer disables gestures on latest Magisk Canary 26.4 (26403) (d7750b72).![magisk_install_log_2023-12-14T15.27.38.txt](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13674726/magisk_install_log_2023-12-14T15.27.38.txt)

**Comment by DanGLES3** [comment]
What device/ROM?

**Comment by innit86** [comment]
> What device/ROM?

Sorry, here:

Pixel 7 Pro
Stock Android 14
November security patch.

It was fine on Canary  26.4 (26402) (1dcf3255)  but updating to 26.4 (26403) (d7750b72) broke something.

**Comment by DanGLES3** [comment]
> > What device/ROM?
> 
> Sorry, here:
> 
> Pixel 7 Pro Stock Android 14 November security patch.
> 
> It was fine on Canary 26.4 (26402) (1dcf3255) but updating to 26.4 (26403) (d7750b72) broke something.

By no longer disables gestures you're referring to the back gestures right?

**Comment by innit86** [comment]
> > > What device/ROM?
> > 
> > 
> > Sorry, here:
> > Pixel 7 Pro Stock Android 14 November security patch.
> > It was fine on Canary 26.4 (26402) (1dcf3255) but updating to 26.4 (26403) (d7750b72) broke something.
> 
> By no longer disables gestures you're referring to the back gestures right?

Yes.

I had this module for a long time (fullscreen with back gestures disabled left and right) . There were no issue up until the newest Magisk Canary dropped. Installing it caused the back gestures to activate. After I noticed it I decided to remove the module and reinstall it with the exact same settings as before. Although it hides the navbar, it does not deactivate the back gestures anymore.

Magisk changelog says "[Zygisk] Introduce new code injection mechanism". Can this be the culprit?

**Comment by DanGLES3** [comment]
> > > > What device/ROM?
> > > 
> > > 
> > > Sorry, here:
> > > Pixel 7 Pro Stock Android 14 November security patch.
> > > It was fine on Canary 26.4 (26402) (1dcf3255) but updating to 26.4 (26403) (d7750b72) broke something.
> > 
> > 
> > By no longer disables gestures you're referring to the back gestures right?
> 
> Yes.
> 
> I had this module for a long time (fullscreen with back gestures disabled left and right) . There were no issue up until the newest Magisk Canary dropped. Installing it caused the back gestures to activate. After I noticed it I decided to remove the module and reinstall it with the exact same settings as before. Although it hides the navbar, it does not deactivate the back gestures anymore.
> 
> Magisk changelog says "[Zygisk] Introduce new code injection mechanism". Can this be the culprit?

Doesn't seem like it, oddly the command is running fine 

Get a terminal app like termux and try running the following commands 

su -c settings put secure back_gesture_inset_scale_left -20

su -c settings put secure back_gesture_inset_scale_right -20

**Comment by innit86** [comment]
I've just installed v25 and everything is back to normal. Thanks.

**Comment by DanGLES3** [comment]
Good to know
