### ISSUE TITLE
Tablet Android 13 - full screen and immersive mode does not work

### ISSUE THREAD

**Issue by vanarok** [Magisk-Modules-Alt-Repo/HideNavBar#59]
I am using unmodified pixel launcher on my tablet. Please write me what I need to do to fix the problem.

**Comment by DanGLES3** [comment]
> I am using unmodified pixel launcher on my tablet. Please write me what I need to do to fix the problem.

It's a known issue, on tablets since Android 12L the navigation bar is handled by the launcher (due to the taskbar), i have a rough idea how to fix that tho i'll need some time to make sure my module can accomodate all tablets and not just Pixels

**Comment by DanGLES3** [comment]
> I am using unmodified pixel launcher on my tablet. Please write me what I need to do to fix the problem.

[test9.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13755260/test9.zip)

For now you can try this build, it's a bit hacky but it should work for the Pixel launcher

**Comment by Dracrius** [comment]
Could you do the same hack for Lawnchair or Nova Launcher? I'm using a Lenovo M10 Plus and the pill is driving me nuts. I don't mind it on a phone but it takes up to much room on a tablet in landscape. I love the Pixel Launcher on my phone but I can't get it to run on my Lenovo so Lawnchair support would work!

**Comment by noahhhi** [comment]
> > I am using unmodified pixel launcher on my tablet. Please write me what I need to do to fix the problem.
> 
> [test9.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13755260/test9.zip)
> 
> For now you can try this build, it's a bit hacky but it should work for the Pixel launcher

Is there any possible to improve it?  Android 14 tablets still leak a small piece of navbar.

**Comment by DanGLES3** [comment]
> > > I am using unmodified pixel launcher on my tablet. Please write me what I need to do to fix the problem.
> > 
> > 
> > [test9.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13755260/test9.zip)
> > For now you can try this build, it's a bit hacky but it should work for the Pixel launcher
> 
> Is there any possible to improve it? Android 14 tablets still leak a small piece of navbar.

Tried disabling the Gcam fix?

**Comment by noahhhi** [comment]
Yes, it half worked.

DanGLES3 ***@***.***> 于 2024年4月25日周四 19:48写道：
