### ISSUE TITLE
Fail to install on Android 14 system API 34

### ISSUE THREAD

**Issue by castiel-zhu** [Magisk-Modules-Alt-Repo/HideNavBar#60]
self-explanatory

Magisk logs:

- Copying zip to temp directory
- Installing Immersive-Gestures-.QT._v13.0_.42.zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/qizdpg.ur/cache/flash/install.zip
  inflating: module.prop
*************************************
 Fullscreen/Immersive Gestures (Q-T) 
 by DanGLES3 
*************************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/qizdpg.ur/cache/flash/install.zip
  inflating: customize.sh
**************************************
*   MMT Extended by Zackptg5 @ XDA   *
**************************************
 
! Your system API of 34 is greater than the maximum api of 33! Aborting!
! Installation failed

**Comment by DanGLES3** [comment]
> self-explanatory
> 
> Magisk logs:
> 
> * Copying zip to temp directory
> * Installing Immersive-Gestures-.QT._v13.0_.42.zip
> * Current boot slot: _b
> * Device is system-as-root
>   Archive:  /data/user/0/qizdpg.ur/cache/flash/install.zip
>   inflating: module.prop
> 
> Fullscreen/Immersive Gestures (Q-T) by DanGLES3
> 
> Powered by Magisk
> 
> Archive: /data/user/0/qizdpg.ur/cache/flash/install.zip inflating: customize.sh
> 
> * MMT Extended by Zackptg5 @ XDA   *
> 
> ! Your system API of 34 is greater than the maximum api of 33! Aborting! ! Installation failed

That version is ancient, right now it's at version 25.0
