### ISSUE TITLE
Doesn't work with 3-button mode anymore

### ISSUE THREAD

**Issue by Traaanaelle** [Magisk-Modules-Alt-Repo/HideNavBar#61]
The module doesn't work with 3-button mode, the system automatically switches to gestures mode, even if you try to change the parameter manually, whereas the module used to work with 3-button mode before.

![Screenshot_20240107-004236](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/assets/63869398/171f0291-dc32-491d-9673-c5e2ed4ea6a5)

**Comment by DanGLES3** [comment]
> The module doesn't work with 3-button mode, the system automatically switches to gestures mode, even if you try to change the parameter manually, whereas the module used to work with 3-button mode before.
> 
> ![Screenshot_20240107-004236](https://private-user-images.githubusercontent.com/63869398/294722885-171f0291-dc32-491d-9673-c5e2ed4ea6a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzI0NjIsIm5iZiI6MTcwNDc3MjE2MiwicGF0aCI6Ii82Mzg2OTM5OC8yOTQ3MjI4ODUtMTcxZjAyOTEtZGMzMi00OTFkLTk2NzMtYzVlMmVkNGVhNmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAzNDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDI5M2M3ZDdkOTA4YzJkNWIzNTJhMzIxMjhmNzhjYzkwMzIxZjM5NjFkNjNiNGNiYTMyMzdiYWFmYjczMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GknyvavQ41vkQOOBWp6wAeqbT10EB8cZb26tlMQn5eE)

This was changed because some devices had compatibility issues with that old method, it really wasn't something I wanted to do (even I enjoyed that seamlessness) but for the sake of compatibility I've had to do this

**Comment by Traaanaelle** [comment]
Wasn't there a way to integrate a choice when installing the module using the volume keys to activate or deactivate this change?

**Comment by DanGLES3** [comment]
> Wasn't there a way to integrate a choice when installing the module using the volume keys to activate or deactivate this change?

While it is feasible I chose not to add it to reduce feature creep and further user confusion of trying to explain an option that functionally wouldn't mean much for most users

Does that sound reasonable to you?

**Comment by Traaanaelle** [comment]
Yes, of course, can you tell me which is the most recent version that does not include this change though?

**Comment by DanGLES3** [comment]
> Yes, of course, can you tell me which is the most recent version that does not include this change though?

That'd be version 23 and below, i don't have that one posted here rn but here's an build of it 
[KSU-test-2.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/13872925/KSU-test-2.zip)

**Comment by Traaanaelle** [comment]
Thanks a lot for your help!
