### ISSUE TITLE
Some applications may have the following white bars. How to solve this problem? Miui Extra does not have this white area, but it consumes too much power. Is it possible for our module to fix this area?

### ISSUE THREAD

**Issue by Tampledb** [Magisk-Modules-Alt-Repo/HideNavBar#70]
![Screenshot_2024-04-17-22-06-37-262_com.steampy.app.jpg](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/assets/96903051/10b7a306-a5e1-4c0d-b6d3-1108c284c668)

**Comment by DanGLES3** [comment]
> ![Screenshot_2024-04-17-22-06-37-262_com.steampy.app.jpg](https://private-user-images.githubusercontent.com/96903051/323277272-10b7a306-a5e1-4c0d-b6d3-1108c284c668.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA3MjcsIm5iZiI6MTcxMzM4MDQyNywicGF0aCI6Ii85NjkwMzA1MS8zMjMyNzcyNzItMTBiN2EzMDYtYTVlMS00YzBkLWI2ZDMtMTEwOGMyODRjNjY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTY3MTAyMzI5ZWMxNmExODJhMDFmNWY4YTU1YTQ3ZmVlNjY4NWIwM2MwYjU2YWRhOTNjN2E1M2RiMzZhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Il0hm0vf2pNVEydGVkh2XadOE42vnJhSRn2E4VLCynM)

Don't use the gcam fix option

**Comment by Tampledb** [comment]
> > ![Screenshot_2024-04-17-22-06-37-262_com.steampy.app.jpg](https://private-user-images.githubusercontent.com/96903051/323277272-10b7a306-a5e1-4c0d-b6d3-1108c284c668.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA3MjcsIm5iZiI6MTcxMzM4MDQyNywicGF0aCI6Ii85NjkwMzA1MS8zMjMyNzcyNzItMTBiN2EzMDYtYTVlMS00YzBkLWI2ZDMtMTEwOGMyODRjNjY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTY3MTAyMzI5ZWMxNmExODJhMDFmNWY4YTU1YTQ3ZmVlNjY4NWIwM2MwYjU2YWRhOTNjN2E1M2RiMzZhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Il0hm0vf2pNVEydGVkh2XadOE42vnJhSRn2E4VLCynM)
> 
> Don't use the gcam fix option

But this will cause the small white bar to not automatically adjust its color according to the display, and it will always display white.

**Comment by DanGLES3** [comment]
> > > ![Screenshot_2024-04-17-22-06-37-262_com.steampy.app.jpg](https://private-user-images.githubusercontent.com/96903051/323277272-10b7a306-a5e1-4c0d-b6d3-1108c284c668.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA3MjcsIm5iZiI6MTcxMzM4MDQyNywicGF0aCI6Ii85NjkwMzA1MS8zMjMyNzcyNzItMTBiN2EzMDYtYTVlMS00YzBkLWI2ZDMtMTEwOGMyODRjNjY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTY3MTAyMzI5ZWMxNmExODJhMDFmNWY4YTU1YTQ3ZmVlNjY4NWIwM2MwYjU2YWRhOTNjN2E1M2RiMzZhOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Il0hm0vf2pNVEydGVkh2XadOE42vnJhSRn2E4VLCynM)
> > 
> > 
> > Don't use the gcam fix option
> 
> But this will cause the small white bar to not automatically adjust its color according to the display, and it will always display white.

Unfortunately that's the only fix for this issue
