### ISSUE TITLE
Back gesture disabling

### ISSUE THREAD

**Issue by rabaimorp** [Magisk-Modules-Alt-Repo/HideNavBar#72]
I wanted to disable only he left back gesture for termux, but chosing to disable only the left does the same thing as chosing to disable both. It disables all back gestures in portrait mode and and everything in landscape mode except if I pull from the nabar.

**My setup**
Android Version: 14 (aosp)
LineageOS Version: 21-20240217
Magisk version: 27.0 (27000)

**Comment by DanGLES3** [comment]
> I wanted to disable only he left back gesture for termux, but chosing to disable only the left does the same thing as chosing to disable both. It disables all back gestures in portrait mode and and everything in landscape mode except if I pull from the nabar.
> 
> **My setup** Android Version: 14 (aosp) LineageOS Version: 21-20240217 Magisk version: 27.0 (27000)

I'd suggest trying the online tutorials for disabling the back gesture
