### ISSUE TITLE
Accidental Google Lens triggering

### ISSUE THREAD

**Issue by Robert-K** [Magisk-Modules-Alt-Repo/HideNavBar#74]
I recently upgraded to Android AP1A.240305.019.A1. 

The fullscreen mode works fine, no pill, keyboard at the bottom etc.

However, since upgrading I frequently trigger some Google Lens feature while using the keyboard. 

I assume it has to do with swiping at the bottom of the screen, but I wasn't able to replicate it intentionally.

**Comment by DanGLES3** [comment]
> I recently upgraded to Android AP1A.240305.019.A1.
> 
> The fullscreen mode works fine, no pill, keyboard at the bottom etc.
> 
> However, since upgrading I frequently trigger some Google Lens feature while using the keyboard.
> 
> I assume it has to do with swiping at the bottom of the screen, but I wasn't able to replicate it intentionally.

You chose low or high sensitivity when installing it?

**Comment by Robert-K** [comment]
Tried it with both options, experienced the same issue regardless.

**Comment by DanGLES3** [comment]
> Tried it with both options, experienced the same issue regardless.

Then either switch to immersive (not hiding keyboard bar) or if you're using Gboard, use Rboard to add some spacing to the bottom of Gboard

https://github.com/DerTyp7214/RboardThemeManagerV3/releases

Swipe up in the bottom menu, flags

**Comment by Robert-K** [comment]
I noticed it's not actually tied to the gboard. Since the latest update, pressing and holding at the bottom center of the screen triggers google lens. Haven't found a way to disable it yet but it doesn't seem to be tied to this module directly.
