### ISSUE TITLE
Volume key selection time way too short to read options

### ISSUE THREAD

**Issue by zwk2160** [Magisk-Modules-Alt-Repo/HideNavBar#77]
Volume key selection time way too short to read options, will cause a lot of issues due to that

**Comment by zwk2160** [comment]
"volume key no detected occurs only for less than 1s, did you really test your module carefully???

**Comment by DanGLES3** [comment]
> "volume key no detected occurs only for less than 1s, did you really test your module carefully???

I've already increased the delay in the volume selector but it seems inconsistent across users, if you have any clue why fell free to tell me?

I and many other users can't replicate this bug

**Comment by DanGLES3** [comment]
> "volume key no detected occurs only for less than 1s, did you really test your module carefully???

Made sure to test it for days prior to the update release but I'll look into the issue

**Comment by zwk2160** [comment]
My device is Lenovo Legion Y70, with a custom build CAF ROM, so I couldn't find out the exact cause here.

**Comment by DanGLES3** [comment]
> My device is Lenovo Legion Y70, with a custom build CAF ROM, so I couldn't find out the exact cause here.

I might have nailed down the cause of the issue and will publish an update shortly, I appreciate the feedback even tho it was a tad bit harsh

**Comment by zwk2160** [comment]
The device is not a popular model so maybe it use strange volume keys but I don't know

**Comment by DanGLES3** [comment]
> The device is not a popular model so maybe it use strange volume keys but I don't know
[27.1.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/15309260/27.1.zip)

See if it's better in this build

**Comment by zwk2160** [comment]
> > The device is not a popular model so maybe it use strange volume keys but I don't know
> 
> [27.1.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/15309260/27.1.zip)
> 
> See if it's better in this build

I think it's better, thx for quick fix

**Comment by DanGLES3** [comment]
> > > The device is not a popular model so maybe it use strange volume keys but I don't know
> > 
> > 
> > [27.1.zip](https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/files/15309260/27.1.zip)
> > See if it's better in this build
> 
> I think it's better, thx for quick fix

If you could confirm 100% that it's better i'd appreciate it, thanks for the report

**Comment by zwk2160** [comment]
Quickly feedback and fixed on my device Lenovo legion Y70 with CAF costom ROM
