### ISSUE TITLE
Your app completely broke my phone, can't use back gesture anymore, mobile data stopped working etc

### ISSUE THREAD

**Issue by afrokilla** [Magisk-Modules-Alt-Repo/HideNavBar#80]
After installing back gesture has completely stopped working. Top status bar is limited. Can't uninstall this module. Mobile data stopped working. Is there anyway to completely remove this module?

Edit: app replaced with module. I'm a bit busy and frustrated right now.

**Comment by DanGLES3** [comment]
> After installing back gesture has completely stopped working. Top status bar is limited. Can't uninstall this app. Mobile data stopped working. Is there anyway to completely remove this app?

App? What app?

**Comment by DanGLES3** [comment]
> I meant module

So, what do you mean by can't uninstall it exactly?

**Comment by afrokilla** [comment]
> > I meant module
> 
> So, what do you mean by can't uninstall it exactly?

So when I uninstall, the back gesture doesn't come back and a back arrow in the navbar section remains even though I have gesture navigation activated. Not 3 button. When I choose 3 button navigation only the back button works. Home and recent doesn't do anything.

**Comment by DanGLES3** [comment]
> > > I meant module
> > 
> > 
> > So, what do you mean by can't uninstall it exactly?
> 
> So when I uninstall, the back gesture doesn't come back and a back arrow in the navbar section remains even though I have gesture navigation activated. Not 3 button. When I choose 3 button navigation only the back button works. Home and recent doesn't do anything.

For the back gesture to return you need to install the module again and choose to not disable the back gesture (the back gesture is enabled/disabled by changing a system setting, that's why just removing the module won't bring it back) you can remove the module afterwards

**Comment by afrokilla** [comment]
> > I meant module
> 
> So, what do you mean by can't uninstall it exactly?

So when I uninstall, the back gesture doesn't come back and a back arrow in the navbar section remains even though I have gesture navigation activated. Not 3 button. When I choose 3 button navigation only the back button works. Home and recent doesn't do anything.

> > > > I meant module
> > > 
> > > 
> > > So, what do you mean by can't uninstall it exactly?
> > 
> > 
> > So when I uninstall, the back gesture doesn't come back and a back arrow in the navbar section remains even though I have gesture navigation activated. Not 3 button. When I choose 3 button navigation only the back button works. Home and recent doesn't do anything.
> 
> For the back gesture to return you need to install the module again and choose to not disable the back gesture (the back gesture is enabled/disabled by changing a system setting, that's why just removing the module won't bring it back) you can remove the module afterwards

I always choose NOT to disable the back gesture. Even when I first installed it. That's the problem. I've never selected disabled back gesture YET it still disabled it. Even when I reinstall and choose not to disable back gesture it disabled it.

**Comment by DanGLES3** [comment]
> > > I meant module
> > 
> > 
> > So, what do you mean by can't uninstall it exactly?
> 
> So when I uninstall, the back gesture doesn't come back and a back arrow in the navbar section remains even though I have gesture navigation activated. Not 3 button. When I choose 3 button navigation only the back button works. Home and recent doesn't do anything.
> 
> > > > > I meant module
> > > > 
> > > > 
> > > > So, what do you mean by can't uninstall it exactly?
> > > 
> > > 
> > > So when I uninstall, the back gesture doesn't come back and a back arrow in the navbar section remains even though I have gesture navigation activated. Not 3 button. When I choose 3 button navigation only the back button works. Home and recent doesn't do anything.
> > 
> > 
> > For the back gesture to return you need to install the module again and choose to not disable the back gesture (the back gesture is enabled/disabled by changing a system setting, that's why just removing the module won't bring it back) you can remove the module afterwards
> 
> I always choose NOT to disable the back gesture. Even when I first installed it. That's the problem. I've never selected disabled back gesture YET it still disabled it. Even when I reinstall and choose not to disable back gesture it disabled it.

That's definitely strange, guess your  device handles this setting in a strange way, perhaps try changing the back gesture sensitivity if your device allows for such 


if not changing both these settings with adb to a decently high value 10-20 and up will work 

settings put secure back_gesture_inset_scale_left
settings put secure back_gesture_inset_scale_right

**Comment by DanGLES3** [comment]
> What about my systemUi being completely messed up too. Can't see notifications anymore. Can't turn on mobile data etc

That's definitely weird, you can try clearing your device's resource cache in /data/resource-cache and reboot

**Comment by afrokilla** [comment]
> > What about my systemUi being completely messed up too. Can't see notifications anymore. Can't turn on mobile data etc
> 
> That's definitely weird, you can try clearing your device's resource cache in /data/resource-cache and reboot

Didn't work. My phone is completely f**ked now. Lol. Does this kernelSU have anything to do with this? I'm using magisk for SU

**Comment by DanGLES3** [comment]
> > > What about my systemUi being completely messed up too. Can't see notifications anymore. Can't turn on mobile data etc
> > 
> > 
> > That's definitely weird, you can try clearing your device's resource cache in /data/resource-cache and reboot
> 
> Didn't work. My phone is completely f**ked now. Lol. Does this kernelSU have anything to do with this? I'm using magisk for SU

No, try perhaps clearing the package cache as well in data/system

**Comment by DanGLES3** [comment]
> I've just played around with this module. Flashed through Magisk 26 on a LineageOS 20.
> 
> It works fine for most part but was unable to boot afterwards (the LOS boot animation was stuck in a loop) until I went back to the TWRP and cleaned Dalvik + Cache. The same was for uninstalling it but not disabling (rebooted after every change). While disabled it acted like completely wiped and it's settings were gone.
> 
> I tested it mainly to get rid of the navigation bar in a keyboard but there is a glitch in landscape mode when bottom keyboard buttons are using by long pressing them and moving the finger up to take a 2nd action. This action interacts with gestures. The keyboard show a popup for each bottom key but every slide of a finger up to choose eg emojis result in going back to the desktop or recent apps list. I'm using the HeliBoard keyboard and there is a "bottom padding scale" setting which lift keyboard buttons up and the whole navigation is smaller or bigger but never completely gone. Unfortunately this isn't working in landscape mode when this module is loaded. Only portrait.

Are you sure you've fleshed the latest version? I'm pretty sure I've added support for a landscape mode in my code for the few ROMs that need a specific landscape value. As for the keyboard space, have you been sure to select the option to disable the keyboard space completely during module install?
