### ISSUE TITLE
System API 35 ist greater than Maximum API of 34

### ISSUE THREAD

**Issue by TimStebner** [Magisk-Modules-Alt-Repo/HideNavBar#81]
Hello, I have updated my device to Android 15 Beta 3 and now the API hast changed to 35. Will there be an Update to Support the latest API?

**Comment by exolon** [comment]
Same here... Worked fine too, until today when for some reason it stopped working and I can't reinstall 😐

**Comment by DanGLES3** [comment]
[27.3 (1).zip](https://github.com/user-attachments/files/16088264/27.3.1.zip)


This should do for now, my computer is not working well atm so it's harder to work on my modules

**Comment by exolon** [comment]
Yup that installed nicely, though it doesn't work for me. 

I do wonder though - the only change I did today was that I updated my Magisk Alpha to 270003, could that be the culprit?

**Comment by DanGLES3** [comment]
> Yup that installed nicely, though it doesn't work for me.
> 
> I do wonder though - the only change I did today was that I updated my Magisk Alpha to 270003, could that be the culprit?

Not sure, are you using any hiding modules? what options you chose during install?

**Comment by exolon** [comment]
Same modules I always used, hide navbar and side, not disabling gestures, no color fix. 

I use Shamiko (updated today as well), interesting that this would matter. Let me disable it and see!

**Comment by exolon** [comment]
Disabled Shamiko, still no effect from the module. Hmmm...

**Comment by DanGLES3** [comment]
> Disabled Shamiko, still no effect from the module. Hmmm...

Could you provide the result of the following command run from a terminal app like Termux?

su -c cmd overlay list | grep gestural

**Comment by exolon** [comment]
Yes, of course: 

$ su -c cmd overlay list | grep gestural
[x] com.android.internal.systemui.navbar.gestural
 [x] com.android.internal.systemui.navobar.gestural
~ $

**Comment by DanGLES3** [comment]
> Yes, of course:
> 
> $ su -c cmd overlay list | grep gestural [x] com.android.internal.systemui.navbar.gestural [x] com.android.internal.systemui.navobar.gestural ~ $

Huh, the overlay is present, that's weird, i think Alpha might have broken something i'm not sure

**Comment by exolon** [comment]
Could well be so. Maybe you could ask on TG to see if anyone else uses Alpha with the same issues?

**Comment by 1355656377** [comment]
> [27.3 (1).zip](https://github.com/user-attachments/files/16088264/27.3.1.zip)
> 
> This should do for now, my computer is not working well atm so it's harder to work on my modules, apologies

It works perfectly on my Pixel 8 A15 240517.

**Comment by Locoman666** [comment]
> [27.3 (1).zip](https://github.com/user-attachments/files/16088264/27.3.1.zip)
> 
> This should do for now, my computer is not working well atm so it's harder to work on my modules, apologies

Cheers! This is my first post here. [DanGLES3](https://github.com/DanGLES3), this zip was pointed out to me by synesthete on XDA. It works perfectly for me (I'm on android 15 beta), thank you. 

My wife thinks I'm crazy, but the thought of seeing that nav pill and the wasted space... it would absolutely drive me mad. And don't even get me started on the status bar ;-)

**Comment by DanGLES3** [comment]
> > [27.3 (1).zip](https://github.com/user-attachments/files/16088264/27.3.1.zip)
> > This should do for now, my computer is not working well atm so it's harder to work on my modules, apologies
> 
> Cheers! This is my first post here. [DanGLES3](https://github.com/DanGLES3), this zip was pointed out to me by synesthete on XDA. It works perfectly for me (I'm on android 15 beta), thank you.
> 
> My wife thinks I'm crazy, but the thought of seeing that nav pill and the wasted space... it would absolutely drive me mad. And don't even get me started on the status bar ;-)

Glad you like it, and yeah the navbar is just an agonizing waste of space

**Comment by smemsh** [comment]
Looks like edge-to-edge is now the default in apps targeting Android 15 API level, so the wasted space will eventually be gone when apps update, but that silly pill is still there drawing over everything.

Can anyone confirm that this module is still usable with the formal Android 15 released just yesterday? README for this project says it only supports to Android 14.  

If we use above zipfile, it works ok with October's Android 15 release (factory images now available)? Maybe it should be released and README file updated, if so...

**Comment by DanGLES3** [comment]
> Looks like edge-to-edge is now the default in apps targeting Android 15 API level, so the wasted space will eventually be gone when apps update, but that silly pill is still there drawing over everything.
> 
> Can anyone confirm that this module is still usable with the formal Android 15 released just yesterday? README for this project says it only supports to Android 14.
> 
> If we use above zipfile, it works ok with October's Android 15 release (factory images now available)? Maybe it should be released and README file updated, if so...

An user already confirmed that it works on Android 15

**Comment by smemsh** [comment]
> An user already confirmed that it works on Android 15

A beta, yes.  The official release may have additional changes.  I'll try testing it later and post back whether it works.

**Comment by exolon** [comment]
Works even on 15 qpr which is supposedly ahead of 15 stable

**Comment by i5lee8bit** [comment]
> > An user already confirmed that it works on Android 15
> 
> A beta, yes. The official release may have additional changes. I'll try testing it later and post back whether it works.

Yes, the zip posted earlier in this thread by the dev works on A15 stable on Pixel 9 Pro XL komodo.

**Comment by smemsh** [comment]
Not working for me:

Phone: Pixel 6 Pro
Android: 15 (AP3A.241005.015)

Only other Magisk module is Systemless Hosts.  In Magisk Modules dialog, the version says `v27.3 by DanGLES3`, it does not have a `.1`, although I downloaded it from the zipfile linked above in this issue.  With September (A14) update I was using Fullscreen_Immersive.Gestures.Q-S.v9.9.37, successfully.  I uninstalled it, flashed the October update (A15), booted, installed above zip in Magisk, rebooted, and no luck.  Tried a few times.

With it installed, the screen contents do occupy slightly more of the screen (bottom is lower), but the pill doesn't disappear.  Instead the pill overwrites the bottom portion of what's on the screen (for example it writes directly over top of the "Superuser" and "Logs" text in Magisk, whereas uninstalled these words are unobscured, just above the pill bar).
```
raven:/ # cmd overlay list | grep gestural
[x] com.android.internal.systemui.navbar.gestural
[x] com.android.internal.systemui.navobar.gestural
```

Answers to install questions:
- Hide the navigation bar? YES
- Hide space under the keyboard? NO
- Hide pill and keep keyboard height/space? YES
- Hide keyboard buttons? NO
- Reduce the size of the keyboard bar? NO
- Disable bottom gestures? NO
- Pick the gesture sensitivity. LOW
- Enable Navbar color fix? NO
- Wish to disable the back gesture? NO

**Comment by smemsh** [comment]
So I tried changing the MAXAPI to 40 in my old Fullscreen_Immersive.Gestures.Q-S.v9.9.37.zip, installed it, and that one works!  Unclear why the newer HideNavBar does not work.

**Comment by DanGLES3** [comment]
> So I tried changing the MAXAPI to 40 in my old Fullscreen_Immersive.Gestures.Q-S.v9.9.37.zip, installed it, and that one works! Unclear why the newer HideNavBar does not work.

Tried hiding both navigation bar and keyboard bar on 27.3?

**Comment by smemsh** [comment]
> Tried hiding both navigation bar and keyboard space on 27.3?

Bingo, that works! Nice... I had some issues before when hiding keyboard space, but I don't remember what they were, it's been years.  I'll try keeping it like this for a while and see if anything comes up.

To clarify, now working on 27.3.1 is:
```
Hide the navigation bar? YES
Hide space under the keyboard? YES
Disable bottom gestures? NO
Pick the gesture sensitivity. HIGH
Enable Navbar color fix? NO
Wish to disable the back gesture? NO
```
So maybe the following combination should be disallowed:
```
Hide the navigation bar? YES
Hide space under the keyboard? NO
```

**Comment by two1212** [comment]
It doesn't hide the bottom pill, but the most other options work, mainly keyboard height, nav bar height ones work. 
Since it doesn't hide the pill, I will use Pixel Xpert to do that.

**Comment by two1212** [comment]
Well, I rebooted and now the pill is hidden, guess it just needed a reboot twice?
