### ISSUE TITLE
Cannot remove navigation bar on Tablet, Gestures and Navbar show up at the same time

### ISSUE THREAD

**Issue by NayamAmarshe** [Magisk-Modules-Alt-Repo/HideNavBar#82]
Hi, I installed the module, it didn't work for me since I'm on MIUI so I removed it. However, after uninstalling, I'm unable to remove the navbar. Earlier, enabling gestures would disable the navbar but now both the navbar and gestures are working at the same time.

What should I do to fix this?

Thank you

**Comment by DanGLES3** [comment]
Try perhaps clearing the resource cache in /data and rebooting
