### ISSUE TITLE
Manual settings configuration using Termux still possible?

### ISSUE THREAD

**Issue by silverwings15** [Magisk-Modules-Alt-Repo/HideNavBar#84]
I recall that you could e.g. manually set the keyboard spacing and other values using Termux. is this still possible, and if so what's the command?

**Comment by DanGLES3** [comment]
It's currently disabled as I haven't had the time to work it specially since it's not a widely used feature

**Comment by silverwings15** [comment]
ah that's unfortunate. in that case, would you be so kind as to add a middle ground option for people who just want to hide some of the keyboard spacing but not necessarily all of it? in my case, using swiftkey and with no keyboard spacing, i can't swipe on the spacebar to change language because it's in the gesture activation zone for switching apps instead

**Comment by DanGLES3** [comment]
> ah that's unfortunate. in that case, would you be so kind as to add a middle ground option for people who just want to hide some of the keyboard spacing but not necessarily all of it? in my case, using swiftkey and with no keyboard spacing, i can't swipe on the spacebar to change language because it's in the gesture activation zone for switching apps instead

There's already a small keyboard bar option

**Comment by silverwings15** [comment]
ah my fault, i thought there was only the one setting to hide all the space. tried a few times again and it's working as intended. tyvm!
